### PR TITLE
Issue #45834: Extend 'Condition' column width

### PR DESCRIPTION
**Pull request by Sigmonia**
#### Rationale
Pull forward for #72 : Issue #45834: Extend 'Condition' column width
Since 72 is targeted to the 22.3-SNAPSHOT branch, and we have no planned future releases for 22.3 I want to make sure it gets pulled forward.

#### Related Pull Requests
* #72 

#### Changes
* Expand 'Condition' column

### CODE REVIEW

**Review by labkey-adam — APPROVED** [review]

**Review by labkey-tchad — COMMENTED** [review]
Not strictly necessary. Merges forward get triggered automatically now (should trigger tonight).

**Comment by Sigmonia** [comment]
Ok, I'll let it run tonight and if it isn't needed I'll close this.

**Comment by Sigmonia** [comment]
I don't see an automerge PR, so I merged this one.

**Comment by Sigmonia** [comment]
Found it.

**Pull request merged**
